runtime: python311
service: comic-creation-suite

env_variables:
  GOOGLE_CLOUD_PROJECT: "your-project-id"
  GCS_BUCKET_NAME: "your-bucket-name"

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10 